name: CheckAList

on:
  schedule:
    - cron: "0 * * * *" # 每小时执行一次
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "sync_alist.yaml"  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd $GITHUB_WORKSPACE/.github/scripts
          chmod +x ./*.sh

          export VERSION_FILE="${GITHUB_WORKSPACE}/alist_version.txt"
          touch $VERSION_FILE
          ./check_alist.sh

      - name: Shell
        run: |
          echo "alist_version=${{ env.alist_version }}"
          echo "alist_update=${{ env.alist_update }}" 

          if [ ${{ env.alist_update }} -eq 1 ]
          then
            echo "无更新"
          else
            echo -e "[自动同步AList] $alist_version" > $GITHUB_WORKSPACE/CHANGELOG.md
            echo -e "$alist_version" > $VERSION_FILE 

            git config user.name "github-actions"
            git config user.email "42014615+jing332@users.noreply.github.com"
            git add .
            git commit -m "[bot] Update alist to $alist_version"
            git push
          fi
