name: CheckAList

on:
  schedule:
    - cron: "0 * * * *" # 每小时执行一次
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "sync_alist.yaml"  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd $GITHUB_WORKSPACE/.github/scripts
          chmod +x ./*.sh

          export VERSION_FILE="${GITHUB_WORKSPACE}/alist_version.txt"
          touch $VERSION_FILE
          ./check_alist.sh

          if [ "$alist_update" = "false" ]; then # 无更新
            exit 0
          else # 有更新
            echo -e "[自动同步AList版本]" > $GITHUB_WORKSPACE/CHANGELOG.md
            echo -e 

            git config user.name "github-actions"
            git config user.email "42014615+jing332@users.noreply.github.com"
            git add .
            git commit -m "[bot] Update alist version"
            git push
          fi
